Web ui
Adds the web application user interface

diff --git a/create-image b/create-image
--- a/create-image
+++ b/create-image
@@ -27,6 +27,11 @@ if [ ! -f "target/arm-unknown-linux-gnueabihf/release/rover-server" ]; then
     exit 1
 fi
 
+if [ ! -d "ui/dist" ]; then
+    echo "'ui/dist' not found. Have you run 'cd ui; npm install && npm run build'?"
+    exit 1
+fi
+
 # Unmount drives and general cleanup on exit, the trap ensures this will always
 # run execpt in the most extream cases.
 cleanup() {
@@ -71,13 +76,15 @@ install -Dm755 "${script}" "${mount}/tmp/${script}"
 install -Dm755 "target/arm-unknown-linux-gnueabihf/release/rover-cli" "${mount}/usr/local/bin/rover-cli"
 install -Dm755 "target/arm-unknown-linux-gnueabihf/release/rover-server" "${mount}/usr/local/bin/rover-server"
 install -Dm755 "src/bin/rover-server.service" "${mount}/etc/systemd/system/rover-server.service"
+mkdir -p  /srv/rover/ui
+cp -r ui/dist/* "/srv/rover/ui/"
 
 # Prep the chroot
-mount -t proc none ${mount}/proc
-mount -t sysfs none ${mount}/sys
-mount -o bind /dev ${mount}/dev
-rm ${mount}/etc/resolv.conf
-cp /etc/resolv.conf ${mount}/etc/resolv.conf
-cp /usr/bin/qemu-arm-static ${mount}/usr/bin/
+mount -t proc none "${mount}/proc"
+mount -t sysfs none "${mount}/sys"
+mount -o bind /dev "${mount}/dev"
+rm "${mount}/etc/resolv.conf"
+cp /etc/resolv.conf "${mount}/etc/resolv.conf"
+cp /usr/bin/qemu-arm-static "${mount}/usr/bin/"
 
 chroot ${mount}  "/tmp/${script}"
